import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fff8f4",
        "surface-dim": "#dfd9d5",
        "surface-container-low": "#f9f2ef",
        "surface-container": "#f3ede9",
        "surface-container-high": "#ede7e3",
        "surface-container-highest": "#e7e1de",
        "surface-variant": "#e7e1de",
        "on-surface": "#1d1b19",
        "on-surface-variant": "#4f453f",
        "on-surface-muted": "#81756e",
        primary: "#554034",
        "primary-dark": "#3d2c22",
        "primary-container": "#6e574a",
        "on-primary": "#ffffff",
        "primary-fixed": "#fcdccb",
        "primary-fixed-dim": "#dfc0b0",
        "on-primary-fixed": "#28180e",
        "inverse-surface": "#32302e",
        "inverse-surface-deep": "#1d1b19",
        "inverse-on-surface": "#f6efec",
        "inverse-on-surface-dim": "#c8bfb8",
        outline: "#81756f",
        "outline-variant": "#d2c4bc",
        tertiary: "#4c433d",
        "tertiary-container": "#645a54",
        "tertiary-fixed": "#efe0d7",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        success: "#3d6b4f",
        "success-container": "#d4eddc",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Georgia", "serif"],
        body: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-dm-mono)", "monospace"],
      },
      fontSize: {
        "display-2xl": ["80px", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.15", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-md": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "1.45", fontWeight: "500" }],
        "body-xl": ["20px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "1", letterSpacing: "0.06em", fontWeight: "500" }],
        "price-lg": ["24px", { lineHeight: "1", fontWeight: "400" }],
        "price-md": ["18px", { lineHeight: "1", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      spacing: {
        section: "128px",
        "section-mobile": "64px",
        gutter: "32px",
        "gutter-mobile": "16px",
        margin: "64px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        content: "1280px",
        reading: "640px",
        narrow: "800px",
      },
      borderRadius: {
        DEFAULT: "2px",
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "8px",
      },
      transitionTimingFunction: {
        editorial: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        decelerate: "cubic-bezier(0, 0, 0.2, 1)",
        accelerate: "cubic-bezier(0.3, 0, 1, 1)",
        standard: "cubic-bezier(0.2, 0, 0, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
